
// Objective-C API for talking to the following Go packages
//
//	gitlab.adtelligent.com/nexinsight/sdk/core
//
// File is generated by gomobile bind. Do not edit.
#ifndef __NexInsightCore_FRAMEWORK_H__
#define __NexInsightCore_FRAMEWORK_H__

#include "Eventsdk.objc.h"
#include "Universe.objc.h"

#endif
