
// Objective-C API for talking to the following Go packages
//
//	github.com/Nexinsight/ios-sdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __nexinsight_FRAMEWORK_H__
#define __nexinsight_FRAMEWORK_H__

#include "Eventsdk.objc.h"
#include "Universe.objc.h"

#endif
