// Objective-C API for talking to github.com/Nexinsight/ios-sdk Go package.
//   gobind -lang=objc github.com/Nexinsight/ios-sdk
//
// File is generated by gobind. Do not edit.

#ifndef __Eventsdk_H__
#define __Eventsdk_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class EventsdkConfig;
@class EventsdkEvent;
@class EventsdkStats;
@class EventsdkTracker;
@protocol EventsdkLogger;
@class EventsdkLogger;

@protocol EventsdkLogger <NSObject>
- (void)log:(long)level msg:(NSString* _Nullable)msg;
@end

/**
 * Config holds every knob of the SDK. Build it with NewConfig and override the
fields you care about; zero values fall back to the defaults documented on
each field.

Only types supported by gomobile bind are used, so the same struct is usable
from Kotlin and Swift.
 */
@interface EventsdkConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewConfig returns a config with defaults applied for the given app tracker id
and queue database path.
 */
- (nullable instancetype)init:(NSString* _Nullable)appUUID databasePath:(NSString* _Nullable)databasePath;
/**
 * Endpoint is the collector URL for a single event. Defaults to
DefaultEndpoint.
 */
@property (nonatomic) NSString* _Nonnull endpoint;
/**
 * BatchEndpoint is the collector URL for a batch of events. Empty (the
default) derives it from Endpoint by appending "batch" to its path, which
is where the collector serves it.
 */
@property (nonatomic) NSString* _Nonnull batchEndpoint;
/**
 * AppUUID is the encoded app tracker id ("ad" parameter). Required.
 */
@property (nonatomic) NSString* _Nonnull appUUID;
/**
 * DatabasePath is the queue database file. It must live in the app's
private storage (Android: context.getFilesDir(), iOS: Application
Support). Required.
 */
@property (nonatomic) NSString* _Nonnull databasePath;
/**
 * UserAgent is sent verbatim. Strongly recommended: the collector derives
OS, browser and device type from it. On Android pass
WebSettings.getDefaultUserAgent(context). When empty, one is synthesised
from OSName/OSVersion/DeviceModel.
 */
@property (nonatomic) NSString* _Nonnull userAgent;
/**
 * UserAgentSuffix is appended to the (possibly synthesised) user agent,
e.g. "MyApp/3.2.1". Left empty by default to keep server-side parsing
predictable.
 */
@property (nonatomic) NSString* _Nonnull userAgentSuffix;
/**
 * OSName is "Android", "iOS" or "iPadOS"; OSVersion is the release, e.g.
"14" or "17.5". DeviceModel is the marketing/model name, e.g. "Pixel 7".
 */
@property (nonatomic) NSString* _Nonnull osName;
@property (nonatomic) NSString* _Nonnull osVersion;
@property (nonatomic) NSString* _Nonnull deviceModel;
/**
 * AppVersion and AppBuild are recorded in the synthesised user agent suffix
only when UserAgentSuffix is empty and AppName is set.
 */
@property (nonatomic) NSString* _Nonnull appName;
@property (nonatomic) NSString* _Nonnull appVersion;
@property (nonatomic) NSString* _Nonnull appBuild;
/**
 * SessionTimeoutSeconds is the inactivity window after which a new session
id is generated. Defaults to 1800 (30 minutes).
 */
@property (nonatomic) long sessionTimeoutSeconds;
/**
 * BatchSize is how many queued events are picked up per delivery cycle.
Defaults to 50.
 */
@property (nonatomic) long batchSize;
/**
 * MaxBatchEvents is how many events one batch request carries. Defaults to
50 and is capped at 100, the collector's own per-batch limit. Events only
share a request when they share a session, user agent and OS version,
because the collector reads those off the headers.
 */
@property (nonatomic) long maxBatchEvents;
/**
 * UseBatchEndpoint delivers several events per request. Enabled by default;
disable with DisableBatchEndpoint. The SDK also falls back to one request
per event on its own when the collector has no batch endpoint.
 */
@property (nonatomic) BOOL useBatchEndpoint;
/**
 * CompressBatchThresholdBytes gzips batch bodies from that size on.
Defaults to 1024; zero disables compression.
 */
@property (nonatomic) long compressBatchThresholdBytes;
/**
 * FlushIntervalSeconds is how often the pipeline delivers on its own.
Defaults to 15.
 */
@property (nonatomic) long flushIntervalSeconds;
/**
 * IngestBufferSize is the in-memory hand-off capacity. Defaults to 512.
 */
@property (nonatomic) long ingestBufferSize;
/**
 * MaxQueueSize caps stored events; the oldest are dropped past the cap.
Defaults to 10000.
 */
@property (nonatomic) long maxQueueSize;
/**
 * MaxAttempts is the delivery attempt budget per event. Defaults to 12.
Zero or negative means "retry until MaxEventAgeSeconds".
 */
@property (nonatomic) long maxAttempts;
/**
 * BaseBackoffSeconds and MaxBackoffSeconds bound the exponential retry
delay. Default to 2 and 300.
 */
@property (nonatomic) long baseBackoffSeconds;
@property (nonatomic) long maxBackoffSeconds;
/**
 * MaxEventAgeSeconds drops events that stayed undelivered for too long.
Defaults to 86400 (24 hours), which is the window the collector accepts
event times in (its maxEventTimeAge): while SendEventTime is on, an older
event would be rejected anyway. Zero disables age-based dropping.
 */
@property (nonatomic) long maxEventAgeSeconds;
/**
 * RequestTimeoutSeconds bounds a single HTTP attempt. Defaults to 15.
 */
@property (nonatomic) long requestTimeoutSeconds;
/**
 * MaxViewabilityTime clamps the "vt" parameter; the collector rejects
larger values. Defaults to 1800 to match the collector default.
 */
@property (nonatomic) long maxViewabilityTime;
/**
 * SendEventTime reports when each event actually happened on the device (the
"et" parameter) instead of letting the collector timestamp it on receipt.
Enabled by default; disable with DisableEventTime, e.g. for a fleet with
untrustworthy clocks. The collector only accepts event times up to
MaxEventAgeSeconds old and at most five minutes in the future.
 */
@property (nonatomic) BOOL sendEventTime;
/**
 * Debug enables the collector's debug mode ("debug=1"); it needs DebugKey
to be accepted. DevKey marks requests as originating from a developer
build. Both are empty by default.
 */
@property (nonatomic) BOOL debug;
@property (nonatomic) NSString* _Nonnull debugKey;
@property (nonatomic) NSString* _Nonnull devKey;
/**
 * UserID pre-seeds the "uid" parameter; it can also be set at runtime via
Tracker.SetUserID.
 */
@property (nonatomic) NSString* _Nonnull userID;
/**
 * SendInstallIDAsUID sends the SDK-generated install id as "uid" whenever no
explicit user id is set. Off by default: it is a persistent
pseudonymous identifier and should be an informed choice.
 */
@property (nonatomic) BOOL sendInstallIDAsUID;
/**
 * AutoHideOnBackground makes OnBackground emit a hide event for the current
screen with the time it was visible. Enabled by default; disable with
DisableAutoHideOnBackground.
 */
@property (nonatomic) BOOL autoHideOnBackground;
/**
 * DisableAutoHideOnBackground turns the automatic background hide event off.
 */
- (void)disableAutoHideOnBackground;
/**
 * DisableBatchEndpoint makes the SDK send one request per event.
 */
- (void)disableBatchEndpoint;
/**
 * DisableEventTime stops reporting the on-device event time, leaving the
collector to timestamp events when it receives them.
 */
- (void)disableEventTime;
/**
 * SetAppInfo is a convenience setter for the app identity fields.
 */
- (void)setAppInfo:(NSString* _Nullable)name version:(NSString* _Nullable)version build:(NSString* _Nullable)build;
/**
 * SetDeviceInfo is a convenience setter for the three device fields.
 */
- (void)setDeviceInfo:(NSString* _Nullable)osName osVersion:(NSString* _Nullable)osVersion deviceModel:(NSString* _Nullable)deviceModel;
@end

/**
 * Event is a tracking event under construction. Obtain one from
Tracker.NewEvent, fill it in and hand it to Tracker.Track.

It is not safe for concurrent use; build and submit it from one thread.
 */
@interface EventsdkEvent : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * CustomParam returns the value of custom parameter index, or "" when unset.
 */
- (NSString* _Nonnull)customParam:(long)index;
/**
 * SetCustomParam sets custom parameter index (1..7), sent as "cpN". An empty
value removes it.
 */
- (BOOL)setCustomParam:(long)index value:(NSString* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
/**
 * SetOTP sets the one-time identity token, required for ident events.
 */
- (void)setOTP:(NSString* _Nullable)otp;
/**
 * SetPrevScreen sets the previous screen name, sent as the "ref" parameter; the
collector uses it as the session origin.
 */
- (void)setPrevScreen:(NSString* _Nullable)name;
/**
 * SetScreen sets the current screen name, sent as the "cur" parameter.
 */
- (void)setScreen:(NSString* _Nullable)name;
/**
 * SetType overrides the event type. It returns an error for unknown types.
 */
- (BOOL)setType:(NSString* _Nullable)eventType error:(NSError* _Nullable* _Nullable)error;
/**
 * SetUserID overrides the tracker-wide user id for this event.
 */
- (void)setUserID:(NSString* _Nullable)uid;
/**
 * SetViewabilityTime sets how long the screen was visible, in seconds. It is
required for close and hide events and clamped to Config.MaxViewabilityTime.
 */
- (void)setViewabilityTime:(long)seconds;
/**
 * Type returns the event type name.
 */
- (NSString* _Nonnull)type;
@end

/**
 * Stats is a snapshot of pipeline counters.
 */
@interface EventsdkStats : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Enqueued is how many events were accepted by Track.
 */
@property (nonatomic) int64_t enqueued;
/**
 * Persisted is how many reached the database.
 */
@property (nonatomic) int64_t persisted;
/**
 * Delivered is how many the collector accepted.
 */
@property (nonatomic) int64_t delivered;
/**
 * Dropped is how many were discarded (permanent rejection, attempt budget,
age, capacity, unreadable payload).
 */
@property (nonatomic) int64_t dropped;
/**
 * Retried is how many delivery attempts were rescheduled.
 */
@property (nonatomic) int64_t retried;
/**
 * Pending is how many events are on disk right now, or -1 if unknown.
 */
@property (nonatomic) int64_t pending;
/**
 * LastError is the most recent pipeline error, empty if there was none.
 */
@property (nonatomic) NSString* _Nonnull lastError;
@end

/**
 * Tracker is the SDK entry point. Create one per app process, keep it for the
process lifetime and Close it on shutdown.

All methods are safe to call from any thread; none of them performs network
or disk I/O on the calling thread apart from Flush and Close.
 */
@interface EventsdkTracker : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewTracker validates the config, opens the queue database, replays whatever
the previous run left behind and starts the background pipeline.
 */
- (nullable instancetype)init:(EventsdkConfig* _Nullable)cfg;
/**
 * Close flushes the pipeline within timeoutMillis and releases the database.
The tracker is unusable afterwards. Undelivered events stay on disk and are
picked up by the next run.
 */
- (BOOL)close:(long)timeoutMillis error:(NSError* _Nullable* _Nullable)error;
/**
 * CurrentScreen returns the screen name recorded last.
 */
- (NSString* _Nonnull)currentScreen;
/**
 * Flush persists the in-memory buffer and delivers the queue, waiting up to
timeoutMillis. It returns an error when events are still pending afterwards,
which is normal while offline. Do not call it on the UI thread.
 */
- (BOOL)flush:(long)timeoutMillis error:(NSError* _Nullable* _Nullable)error;
/**
 * FlushAsync asks the pipeline to deliver everything queued, without waiting.
 */
- (void)flushAsync;
/**
 * Identify sends an identity sync event carrying a MyGaru OTP.
 */
- (BOOL)identify:(NSString* _Nullable)otp error:(NSError* _Nullable* _Nullable)error;
/**
 * InstallID returns the stable pseudonymous id generated for this installation.
 */
- (NSString* _Nonnull)installID;
- (EventsdkEvent* _Nullable)newEvent:(NSString* _Nullable)eventType;
/**
 * OnBackground should be called when the app is backgrounded. With
Config.AutoHideOnBackground it emits a hide event for the current screen
carrying its visibility time, then triggers a delivery attempt. It does not
block; call Flush if the host app wants to wait.
 */
- (void)onBackground;
/**
 * OnForeground should be called when the app becomes active. It extends or
rotates the session depending on how long the app was away.
 */
- (void)onForeground;
/**
 * PendingCount returns how many events are still queued on disk, or -1 when the
queue cannot be read.
 */
- (int64_t)pendingCount;
/**
 * ResetSession starts a new session immediately, e.g. after a logout. It
returns the new session id.
 */
- (NSString* _Nonnull)resetSession;
/**
 * SessionID returns the current session id, as sent in the X-REMOTE-NISESS
header.
 */
- (NSString* _Nonnull)sessionID;
/**
 * SetLogger installs (or with nil removes) the diagnostics sink.
 */
- (void)setLogger:(id<EventsdkLogger> _Nullable)l;
/**
 * SetScreen records the screen the user is on without emitting an event. The
previous screen is remembered and sent as "ref" on subsequent events.
 */
- (void)setScreen:(NSString* _Nullable)name;
/**
 * SetUserID sets the value sent as the "uid" parameter. Pass "" to clear it.
 */
- (void)setUserID:(NSString* _Nullable)uid;
/**
 * Stats returns a snapshot of the pipeline counters for diagnostics.
 */
- (EventsdkStats* _Nullable)stats;
/**
 * Track queues an event built with NewEvent. It validates the event, stamps it
with the session and device context and returns as soon as the event is in
the in-memory buffer — delivery happens in the background.
 */
- (BOOL)track:(EventsdkEvent* _Nullable)e error:(NSError* _Nullable* _Nullable)error;
/**
 * TrackClose records a screen or app close together with how long the screen
was visible, in seconds.
 */
- (BOOL)trackClose:(NSString* _Nullable)screen viewabilitySeconds:(long)viewabilitySeconds error:(NSError* _Nullable* _Nullable)error;
/**
 * TrackHide records a screen or app going to the background together with how
long the screen was visible, in seconds.
 */
- (BOOL)trackHide:(NSString* _Nullable)screen viewabilitySeconds:(long)viewabilitySeconds error:(NSError* _Nullable* _Nullable)error;
/**
 * TrackHideAuto records a hide event for the current screen, computing the
visibility time from the last TrackView/SetScreen call.
 */
- (BOOL)trackHideAuto:(NSError* _Nullable* _Nullable)error;
/**
 * TrackView records a screen view. It also becomes the current screen, which
starts the visibility timer used by TrackHideAuto/OnBackground.
 */
- (BOOL)trackView:(NSString* _Nullable)screen error:(NSError* _Nullable* _Nullable)error;
/**
 * UserID returns the currently configured user id.
 */
- (NSString* _Nonnull)userID;
@end

/**
 * DefaultEndpoint is the production collector. It is overridable so that a host
app can point the SDK at a staging collector or a local proxy.
 */
FOUNDATION_EXPORT NSString* _Nonnull const EventsdkDefaultEndpoint;
/**
 * EventClose is emitted when a screen or the app is closed; it carries the
time the screen was visible.
 */
FOUNDATION_EXPORT NSString* _Nonnull const EventsdkEventClose;
/**
 * EventHide is emitted when a screen or the app goes to the background; it
carries the time the screen was visible.
 */
FOUNDATION_EXPORT NSString* _Nonnull const EventsdkEventHide;
/**
 * EventIdent is an identity sync event; it requires an OTP.
 */
FOUNDATION_EXPORT NSString* _Nonnull const EventsdkEventIdent;
/**
 * EventView is the default event, emitted when a screen becomes visible.
 */
FOUNDATION_EXPORT NSString* _Nonnull const EventsdkEventView;
/**
 * Log levels passed to Logger.Log.
 */
FOUNDATION_EXPORT const int64_t EventsdkLogDebug;
/**
 * Log levels passed to Logger.Log.
 */
FOUNDATION_EXPORT const int64_t EventsdkLogError;
/**
 * Log levels passed to Logger.Log.
 */
FOUNDATION_EXPORT const int64_t EventsdkLogInfo;
/**
 * Log levels passed to Logger.Log.
 */
FOUNDATION_EXPORT const int64_t EventsdkLogWarn;
/**
 * Version is the SDK core version, reported in the synthesised user agent.
 */
FOUNDATION_EXPORT NSString* _Nonnull const EventsdkVersion;

@interface Eventsdk : NSObject
/**
 * ErrClosed is returned by a tracker that has been closed.
 */
+ (NSError* _Nullable) errClosed;
+ (void) setErrClosed:(NSError* _Nullable)v;

/**
 * ErrNoAppUUID is returned when Config.AppUUID is empty.
 */
+ (NSError* _Nullable) errNoAppUUID;
+ (void) setErrNoAppUUID:(NSError* _Nullable)v;

/**
 * ErrNoDatabasePath is returned when Config.DatabasePath is empty.
 */
+ (NSError* _Nullable) errNoDatabasePath;
+ (void) setErrNoDatabasePath:(NSError* _Nullable)v;

@end

/**
 * NewConfig returns a config with defaults applied for the given app tracker id
and queue database path.
 */
FOUNDATION_EXPORT EventsdkConfig* _Nullable EventsdkNewConfig(NSString* _Nullable appUUID, NSString* _Nullable databasePath);

/**
 * NewTracker validates the config, opens the queue database, replays whatever
the previous run left behind and starts the background pipeline.
 */
FOUNDATION_EXPORT EventsdkTracker* _Nullable EventsdkNewTracker(EventsdkConfig* _Nullable cfg, NSError* _Nullable* _Nullable error);

@class EventsdkLogger;

/**
 * Logger receives SDK diagnostics. Implement it on the platform side to route
them into Logcat or OSLog; without one the SDK stays silent.
 */
@interface EventsdkLogger : NSObject <goSeqRefInterface, EventsdkLogger> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)log:(long)level msg:(NSString* _Nullable)msg;
@end

#endif
